---
grails:
  profile: web
  codegen:
    defaultPackage: gb
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
info:
  app:
    name: "@info.app.name@"
    version: "@info.app.version@"
    grailsVersion: "@info.app.grailsVersion@"
spring:
  jmx:
    unique-names: true
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false
  devtools:
    restart:
      additional-exclude:
        - "*.gsp"
        - "**/*.gsp"
        - "*.gson"
        - "**/*.gson"
        - "logback.groovy"
        - "*.properties"
management:
  endpoints:
    enabled-by-default: false

---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: "*/*"
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
    json:
      compileStatic: false #Development only see http://views.grails.org/latest/#_static_compilation
management:
  endpoints:
    jmx:
      unique-names: true

---
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ""

environments:
  development:
    dataSource:
      logSql: true
      dbCreate: update
      pooled: true
      jmxExport: true
      driverClassName: com.mysql.jdbc.Driver
      username: groupbuydev
      password: gr0up-buy!
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      url: jdbc:mysql://ptah07.seeweb.it:3306/gb-dev
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
  test:
    dataSource:
      dbCreate: none
      pooled: true
      jmxExport: true
      driverClassName: com.mysql.jdbc.Driver
      username: groupbuytest
      password: gr0up-buy!
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      url: jdbc:mysql://ptah07.seeweb.it:3306/gb-test
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
  production:
    dataSource:
      dbCreate: none
      pooled: true
      jmxExport: true
      driverClassName: com.mysql.jdbc.Driver
      username: groupbuy
      password: gr0up-buy!
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      url: jdbc:mysql://ptah07.seeweb.it:3306/gb_prod
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
grails:
  mail:
    port: 1025 #port: 1025
    host: vm8783.seewebcloud.it #host: localhost
    #username: "noreply@group-buy.it"
    #password: "group-buy@noreply"
    props:
      ["mail.smtp.auth": "false", "mail.debug": "true"]
      #"mail.smtp.socketFactory.port": "465",
      #"mail.smtp.socketFactory.class": "javax.net.ssl.SSLSocketFactory",
      #"mail.smtp.socketFactory.fallback": "false",
      #"mail.smtp.starttls.enable": "true",
    serverURL: "http://localhost:8080/"
---
grails:
  plugin:
    databasemigration:
      updateOnStart: false
      updateOnStartFileName: changelog-test.groovy
---
grails:
  plugin:
    springsecurity:
      active: true
      ui:
        register:
          defaultRoleNames: ["ROLE_CUSTOMER"]
          requireEmailValidation: true
          postRegisterUrl: "/utente/benvenuto"

        gsp:
          layoutRegister: "claylist"
---
grails:
  plugin:
    databasemigration:
      dbDocController:
        enabled: true
---
grails:
  asset:
    minifyJs: false
    minifyCss: false
    enableSourceMaps: false
    excludes: ["vue/*.js", "vue/v-*/*"]
